parameters:
    google_analytics_key: 'UA-163559523-1'
    contact_email: 'contact@kargain.world'
    social_networks:
      ##  facebook:
      ##    icon: 'facebook'
      ##    url:  '#facebook'
        twitter:
          icon: 'twitter'
          url:  'https://twitter.com/KargainWorld'
        linkedin:
          icon: 'linkedin'
          url:  'https://www.linkedin.com/showcase/kargain-world/'
      ##   medium:
      ##    icon: 'medium'
      ##    url:  '#medium'
      ##  fling:
      ##    icon: 'plane'
      ##    url:  '#fling'
      ##  github:
      ##    icon: 'github'
      ##    url:  'https://github.com/kargainworld'
        reddit:
          icon: 'reddit'
          url:  '#reddit'
    team:
        member_1:
            lastname:   "Kargain World"
            firstname:  "GitHub"
            avatar:     "/build/images/avatars/github.png"
            url:  'https://github.com/kargainworld'
            job:
              en: "{ClaN}"
              fr: "{ClaN}"

        ## member_1:
        ##     lastname:   "Martha"
        ##     firstname:  "Kane"
        ##     avatar:     "/build/images/avatars/martha-kane.png"
        ##     job:
        ##       en: "Founder (CEO)"
        ##       fr: "Fondatrice (CEO)"
        ## member_2:
        ##     lastname:   "Bruce"
        ##     firstname:  "Wayne"
        ##     avatar:     "/build/images/avatars/bruce-wayne.png"
        ##     job:
        ##       en: "Co-Founder (CEO)"
        ##       fr: "Co-Fondateur (CEO)"
        ## member_3:
        ##     lastname:   "Doe"
        ##     firstname:  "John"
        ##     avatar:     "/build/images/avatars/john-doe.png"
        ##     job:
        ##       en: "Chief Technology Officer (CTO)"
        ##       fr: "Directeur de la technologie (CTO)"
        ## member_4:
        ##    lastname:   "Roth"
        ##    firstname:  "Raven"
        ##    avatar:     "/build/images/avatars/raven-roth.png"
        ##    job:
        ##      en: "Developer"
        ##      fr: "Développeuse"
        ##member_5:
        ##    lastname:   "Morales"
        ##    firstname:  "Miles"
        ##    avatar:     "/build/images/avatars/miles-morales.png"
        ##    job:
        ##      en: "Developer"
        ##      fr: "Développeur"
        ##member_6:
        ##    lastname:   "Portgas D."
        ##    firstname:  "Ace"
        ##    avatar:     "/build/images/avatars/a[s]ce.png"
        ##    job:
        ##      en: "Community Manager"
        ##      fr: "Community Manager"
    partners:
        ray_connection:
            name: "raY Connection"
            logo: "/build/images/partners/ray-connection.png"
        studio_way:
            name: "Studio WAY"
            logo: "/build/images/partners/studio-way.png"
        litti_aurelien:
            name: "Litti Aurélien"
            logo: "/build/images/partners/litti-aurelien.png"
    features:
        item_1:
            icon:   "user"
            title:
              en: "Self-sovereign Identity"
              fr: "Identité auto-souveraine"
            text:
              en: "Own and protect your data."
              fr: "Posséder et protéger vos données."
        item_2:
            icon:   "messages"
            title:
              en: "Encrypted Messaging"
              fr: "Messagerie cryptée"
            text:
              en: "Send secure, private messages to other buyers and sellers on the platform."
              fr: "Envoyez des messages privés et sécurisés à d'autres acheteurs et vendeurs sur la plateforme."
        item_3:
            icon:   "file-exchange"
            title:
              en: "Reputation System"
              fr: "Système de réputation"
            text:
              en: "Give ratings and leave reviews for your transactions."
              fr: "Donnez des notes et laissez des avis pour vos transactions."
        item_4:
            icon:   "cubic"
            title:
              en: "Blockchain-Powered Transactions"
              fr: "Transactions Blockchain-Powerred"
            text:
              en: "Funds are escrowed on our marketplace smart contract."
              fr: "Les fonds sont conservés et sécurisé par le smart contrat."
    milestones:
        item_1:
            date:
              en: "October 2020"
              fr: "Octobre 2020"
            text:
              en: "Development Kargain."
              fr: "Développement Kargain."
        item_2:
            date:
              en: "September 2020"
              fr: "Septembre 2020"
            text:
              en: "Development Kargain."
              fr: "Développement Kargain."
        item_3:
            is_old: true
            date:
              en: "April 2020"
              fr: "Avril 2019"
            text:
              en: "Development Kargain."
              fr: "Développement Kargain."

# services:
#     # ... some services
