<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about.en' => [[], ['_controller' => 'App\\Controller\\AboutController::index', '_locale' => 'en', '_canonical_route' => 'about'], [], [['text', '/']], [], []],
    'about.fr' => [[], ['_controller' => 'App\\Controller\\AboutController::index', '_locale' => 'fr', '_canonical_route' => 'about'], [], [['text', '/fr']], [], []],
    'dashboard_reset_cache' => [[], ['_controller' => 'App\\Controller\\DashboardController::reset_cache'], [], [['text', '/dashboard/reset-cache']], [], []],
    'dashboard' => [['current_page'], ['current_page' => 1, '_controller' => 'App\\Controller\\DashboardController::index'], [], [['variable', '/', '[^/]++', 'current_page', true], ['text', '/dashboard']], [], []],
    'dashboard_newsletter' => [[], ['_controller' => 'App\\Controller\\DashboardNewsletterController::index'], [], [['text', '/dashboard/newsletter']], [], []],
    'dashboard_news_subs_delete' => [['email'], ['_controller' => 'App\\Controller\\DashboardNewsletterController::newsletter_subs_delete'], [], [['variable', '/', '[^/]++', 'email', true], ['text', '/dashboard/newsletter/subscribe/delete']], [], []],
    'dashboard_news_subs_download' => [[], ['_controller' => 'App\\Controller\\DashboardNewsletterController::newsletter_subs_download'], [], [['text', '/dashboard/newsletter/subscribe/download']], [], []],
    'ico.en' => [[], ['_controller' => 'App\\Controller\\ICOController::index', '_locale' => 'en', '_canonical_route' => 'ico'], [], [['text', '/ico']], [], []],
    'ico.fr' => [[], ['_controller' => 'App\\Controller\\ICOController::index', '_locale' => 'fr', '_canonical_route' => 'ico'], [], [['text', '/fr/ico']], [], []],
    'newsletter_subscribe' => [[], ['_controller' => 'App\\Controller\\NewsletterController::subscribe'], [], [['text', '/newsletter/subscribe/']], [], []],
    'organization.en' => [[], ['_controller' => 'App\\Controller\\OrganizationController::index', '_locale' => 'en', '_canonical_route' => 'organization'], [], [['text', '/organization']], [], []],
    'organization.fr' => [[], ['_controller' => 'App\\Controller\\OrganizationController::index', '_locale' => 'fr', '_canonical_route' => 'organization'], [], [['text', '/fr/organisation']], [], []],
    'privacy_policy.en' => [[], ['_controller' => 'App\\Controller\\PrivacyPolicyController::index', '_locale' => 'en', '_canonical_route' => 'privacy_policy'], [], [['text', '/privacy-policy']], [], []],
    'privacy_policy.fr' => [[], ['_controller' => 'App\\Controller\\PrivacyPolicyController::index', '_locale' => 'fr', '_canonical_route' => 'privacy_policy'], [], [['text', '/fr/politique-de-confidentialite']], [], []],
    'product.en' => [[], ['_controller' => 'App\\Controller\\ProductController::index', '_locale' => 'en', '_canonical_route' => 'product'], [], [['text', '/product']], [], []],
    'product.fr' => [[], ['_controller' => 'App\\Controller\\ProductController::index', '_locale' => 'fr', '_canonical_route' => 'product'], [], [['text', '/fr/produit']], [], []],
    'team.en' => [[], ['_controller' => 'App\\Controller\\TeamController::index', '_locale' => 'en', '_canonical_route' => 'team'], [], [['text', '/team']], [], []],
    'team.fr' => [[], ['_controller' => 'App\\Controller\\TeamController::index', '_locale' => 'fr', '_canonical_route' => 'team'], [], [['text', '/fr/l-equipe']], [], []],
    'terms_service.en' => [[], ['_controller' => 'App\\Controller\\TermsServiceController::index', '_locale' => 'en', '_canonical_route' => 'terms_service'], [], [['text', '/terms-service']], [], []],
    'terms_service.fr' => [[], ['_controller' => 'App\\Controller\\TermsServiceController::index', '_locale' => 'fr', '_canonical_route' => 'terms_service'], [], [['text', '/fr/condition-d-utilisation']], [], []],
];
