<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH3e88Uf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH3e88Uf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH3e88Uf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH3e88Uf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH3e88Uf\App_KernelDevDebugContainer([
    'container.build_hash' => 'H3e88Uf',
    'container.build_id' => 'e0f42040',
    'container.build_time' => 1587147414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH3e88Uf');
